import './globals.css'; // ✅ use relative path based on your folder structure
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      
      <body>
        <Navbar/>
        <main>
          {children}
          
        </main>
        </body>
    </html>
  );
}
